database:
  host: "47.108.27.238"
  user: "scu301"
  dbname: "db123"
mqtt:
  host: "47.108.27.238"
  port: 1883
  id: rust-server
  cap: 10
  keep_alive: 5
  topic_status: "/status"
  topic_status_qos: 1
  topic_events: "/events"
  topic_events_qos: 2
actix:
  port: 8123
  ip: 0.0.0.0