### GET request to example server
GET localhost:80/api/test/mqtt
###
POST localhost:80/api/login
Content-Type: application/json

{
  "username": "wzy",
  "password": "123456"
}

> {% client.global.set("local-rust-token", response.body.data.token); %}
###
GET localhost:80/api/my/device
Authorization: Bearer {{local-rust-token}}
###
GET localhost:80/api/my/device/4/switch
Authorization: Bearer {{local-rust-token}}
###

###
POST 47.108.27.238/api/login
Content-Type: application/json

{
  "username": "wzy",
  "password": "123456"
}

> {% client.global.set("remote-rust-token", response.body.data.token); %}

###
GET 47.108.27.238/api/test/mqtt
###
GET 47.108.27.238/api/my/device
Authorization: Bearer {{remote-rust-token}}
###
GET 47.108.27.238/api/my/device/4/switch
Authorization: Bearer {{remote-rust-token}}
###
GET 47.108.27.238/api/sse
Authorization: Bearer {{remote-rust-token}}